import processing.core.*;

import jm.music.data.*;
import jm.JMC;
import jm.util.*;
import jm.midi.*;

import java.io.UnsupportedEncodingException;
import java.net.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class holaThis extends PApplet {
	PFont f; 
	MelodyPlayer player;
	MelodyPlayer generatedNotes;
	MidiFileToNotes midiNotes;
	
	public static void main(String[] args) {
	
	// TODO Auto-generated method stub
	PApplet.main("holaThis");
	
	PSTNode<String> root = new PSTNode<String> (3);
	String[] str = {"a","b","r","a","c","a","d","a","b","r","a"};
	ArrayList<String> data = new ArrayList(Arrays.asList(str));
	root.addToTree(data);
	root.print();
	
	
	
}
	
	
	public void settings() {
		size(900, 800);
	}

	public void setup() {
		background(135,106,250);
	}
		
		
//probability calculations
		
		

	public void draw() {
	
	}
	
	//This will play the music generated by the computer using order of 2
	
}

